[package]
name = "webpki-roots"
version = "0.19.0"
edition = "2018"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
readme = "README.md"
license = "MPL-2.0"
description = "Mozilla's CA root certificates for use with webpki"
homepage = "https://github.com/ctz/webpki-roots"
repository = "https://github.com/ctz/webpki-roots"

[dependencies]
webpki = { git = "https://github.com/veracruz-project/webpki.git", branch = "veracruz-v1" }
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[features]
default = []
mesalock_sgx = ["sgx_tstd", "webpki/mesalock_sgx"]
